// Generated by gencpp from file sensor_stick/GetFloatArrayFeatureResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_STICK_MESSAGE_GETFLOATARRAYFEATURERESPONSE_H
#define SENSOR_STICK_MESSAGE_GETFLOATARRAYFEATURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_stick
{
template <class ContainerAllocator>
struct GetFloatArrayFeatureResponse_
{
  typedef GetFloatArrayFeatureResponse_<ContainerAllocator> Type;

  GetFloatArrayFeatureResponse_()
    : feature()  {
    }
  GetFloatArrayFeatureResponse_(const ContainerAllocator& _alloc)
    : feature(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _feature_type;
  _feature_type feature;





  typedef boost::shared_ptr< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFloatArrayFeatureResponse_

typedef ::sensor_stick::GetFloatArrayFeatureResponse_<std::allocator<void> > GetFloatArrayFeatureResponse;

typedef boost::shared_ptr< ::sensor_stick::GetFloatArrayFeatureResponse > GetFloatArrayFeatureResponsePtr;
typedef boost::shared_ptr< ::sensor_stick::GetFloatArrayFeatureResponse const> GetFloatArrayFeatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator1> & lhs, const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feature == rhs.feature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator1> & lhs, const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_stick

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "294d40af1af59d3ff9b78d3a0d06f00c";
  }

  static const char* value(const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x294d40af1af59d3fULL;
  static const uint64_t static_value2 = 0xf9b78d3a0d06f00cULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_stick/GetFloatArrayFeatureResponse";
  }

  static const char* value(const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] feature\n"
"\n"
;
  }

  static const char* value(const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFloatArrayFeatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_stick::GetFloatArrayFeatureResponse_<ContainerAllocator>& v)
  {
    s << indent << "feature[]" << std::endl;
    for (size_t i = 0; i < v.feature.size(); ++i)
    {
      s << indent << "  feature[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.feature[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_STICK_MESSAGE_GETFLOATARRAYFEATURERESPONSE_H
